name: quickeydb
description: A new Flutter SQLite Wrapper.

homepage: https://github.com/itskenzylimon/quickey

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.3+1
  sqflite_common: ^2.2.1+1
  collection: ^1.15.0-nullsafety.4

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

  flutter_lints: ^2.0.0