name: quickeydb
description: A new Flutter SQLite Wrapper.

homepage: https://github.com/itskenzylimon/quickey

version: 1.0.2+2

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi:
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.3.0

  flutter_lints: ^2.0.0